#
# GNUmakefile - Generated by ProjectCenter
#

include $(GNUSTEP_MAKEFILES)/common.make

#
# Application
#
VERSION = 1.2
PACKAGE_NAME = Thermometer
APP_NAME = Thermometer
Thermometer_APPLICATION_ICON = 
GNUSTEP_INSTALLATION_DIR = $(HOME)/GNUstep


#
# Resource files
#
Thermometer_RESOURCE_FILES = \
Resources/Thermometer.gorm \
Resources/Preferences.gorm\
Resources/therm-c.png \
Resources/therm-f.png\
Resources/Info-gnustep.plist

#
# Header files
#
Thermometer_HEADER_FILES = \
AppController.h \
LempClient.h \
TempReading.h \
ThermController.h \
Thermometer.h \
ThermometerCell.h \
LogController.h \
Readings.h \
LempSource.h \
TempSource.h \
PreferenceController.h

#
# Class files
#
Thermometer_OBJC_FILES = \
AppController.m \
LempClient.m \
TempReading.m \
ThermController.m \
Thermometer.m \
ThermometerCell.m \
LogController.m \
Readings.m \
LempSource.m \
TempSource.m \
PreferenceController.m

#
# C files
#
Thermometer_C_FILES = 

Thermometer_OBJC_FILES += \
main.m 

#
# Makefiles
#
-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/aggregate.make
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble
